In [2]:
import numpy as np

In [161]:
def produceTransformMat(translation = [0, 0, 0], eulerAng = [0, 0, 0]):
    """a rotation and translation expressed in RZ*RY*RX Rotation
    tx = translation[0]
    ty = translation[1]
    tz = translation[2]
    phi = eulerAng[0]
    theta = eulerAng[1]
    psi = eulerAng[2]"""
    m11 = np.cos(eulerAng[0])*np.cos(eulerAng[1])
    m12 = np.cos(eulerAng[0])*np.sin(eulerAng[1])*np.sin(eulerAng[2]) - np.sin(eulerAng[0])*np.cos(eulerAng[2])
    m13 = np.cos(eulerAng[0])*np.sin(eulerAng[1])*np.cos(eulerAng[2]) + np.sin(eulerAng[0])*np.sin(eulerAng[2])
    m14 = translation[0]

    m21 = np.sin(eulerAng[0])*np.cos(eulerAng[1])
    m22 = np.sin(eulerAng[0])*np.sin(eulerAng[1])*np.sin(eulerAng[2]) + np.cos(eulerAng[0])*np.cos(eulerAng[2])
    m23 = np.sin(eulerAng[0])*np.sin(eulerAng[1])*np.cos(eulerAng[2]) - np.cos(eulerAng[0])*np.sin(eulerAng[2])
    m24 = translation[1]

    m31 = -np.sin(eulerAng[1])
    m32 = np.cos(eulerAng[1])*np.sin(eulerAng[2])
    m33 = np.cos(eulerAng[1])*np.cos(eulerAng[2])
    m34 = translation[2]


    return np.array([[m11, m12, m13, m14], [m21, m22, m23, m24], [m31, m32, m33, m34], [0, 0, 0, 1]])



In [162]:
#rot pi/4
np.set_printoptions(suppress=True)
T_1 = produceTransformMat(eulerAng=[np.pi/2, 0, 0])

T_2 = produceTransformMat(eulerAng=[0, np.pi/2, 0])

T_3 = produceTransformMat(eulerAng=[0, 0, np.pi/2])



In [163]:
print('T_1')
print(T_1)

print('T_2')
print(T_2)

print('T_3')
print(T_3)

T_1
[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
T_2
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
T_3
[[ 1.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]


In [174]:
#W = np.array([[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [1, 1, 1, 1]])

#Coord = np.tensordot(W,T_3,axes=((0),(1)))

W = np.array([[0], [0], [1], [1]])
Coord = np.tensordot(T_2,W,axes=((1),(0)))
print(Coord)

[[1.]
 [0.]
 [0.]
 [1.]]


W.shape

In [87]:
T_1.shape

(4L, 4L)